---
- hosts: services
  roles:
    - icinga2-core
    - icinga2-nrpe
    - email-ssmtp

- hosts: mapserver
  roles:
    - icinga2-nrpe

- hosts: gateways
  roles:
    - icinga2-nrpe

- hosts: satellites
  roles:
    - icinga2-nrpe

