- name: install the latest version of icinga2
  package:
    name: icinga2
    state: latest

- name: Clean localhost default config
  file:
    state: absent
    path: "/etc/icinga2/conf.d/hosts/localhost/"

- name: Clean localhost default config
  file:
    state: absent
    path: "/etc/icinga2/conf.d/hosts/localhost.conf"

- name: install the latest version of icinga plugins
  package:
    name: nagios-plugins
    state: latest

- name: install the latest version of nagios-nrpe-plugin
  package:
    name: nagios-nrpe-plugin
    state: latest

- name: install icinga2-classicui
  package:
    name: icinga2-classicui
    state: latest

- name: Install icinga2-classicui nginx site
  template:
    src: icinga2-classicui.j2
    dest: /etc/nginx/sites-available/icinga2-classicui

- name: Make sure we can use htpasswd module
  package:
    name: python-passlib
    state: latest

- htpasswd:
    path: /etc/icinga2/classicui/htpasswd.users
    name: icingaadmin
    password: "{{ icingaadminpw }}"

- name: install fcgiwrap
  package:
    name: fcgiwrap
    state: latest


- name: Configure gateways
  template: "src=srv-gateways.conf.j2 dest='/etc/icinga2/conf.d/hosts/srv-gateways.conf' owner=root group=root"

- name: Configure mapserver
  template: "src=srv-mapserver.conf.j2 dest='/etc/icinga2/conf.d/hosts/srv-mapserver.conf' owner=root group=root"

- name: Configure satellites
  template: "src=srv-satellites.conf.j2 dest='/etc/icinga2/conf.d/hosts/srv-satellites.conf' owner=root group=root"

- name: Configure services
  template: "src=srv-services.conf.j2 dest='/etc/icinga2/conf.d/hosts/srv-services.conf' owner=root group=root"

- name: Configure VIP Nodes
  template: "src=vip-nodes.conf.j2 dest='/etc/icinga2/conf.d/hosts/vip-nodes.conf' owner=root group=root"

- name: Configure Commands
  template: "src=commands.conf.j2 dest='/etc/icinga2/conf.d/commands.conf' owner=root group=root"

- name: Configure Downtimes
  template: "src=downtimes.conf.j2 dest='/etc/icinga2/conf.d/downtimes.conf' owner=root group=root"

- name: Configure Groups
  template: "src=groups.conf.j2 dest='/etc/icinga2/conf.d/groups.conf' owner=root group=root"

- name: Configure notifications
  template: "src=notifications.conf.j2 dest='/etc/icinga2/conf.d/notifications.conf' owner=root group=root"

- name: Configure Services
  template: "src=services.conf.j2 dest='/etc/icinga2/conf.d/services.conf' owner=root group=root"

- name: Configure Templates
  template: "src=templates.conf.j2 dest='/etc/icinga2/conf.d/templates.conf' owner=root group=root"

- name: Configure timeperiods
  template: "src=timeperiods.conf.j2 dest='/etc/icinga2/conf.d/timeperiods.conf' owner=root group=root"

- name: Configure users
  template: "src=users.conf.j2 dest='/etc/icinga2/conf.d/users.conf' owner=root group=root"

#- name: generate Icinga contacts
#  template: "src=contacts.conf.j2 dest=/etc/icinga2/conf.d/contacts.conf' owner=root group=root"
#  when: icinga_admincontacts is defined



#- name: install mysql server
#  package:
#    name: mysql-server
#    state: latest
#
#- name: install mysql client                 
#  package:
#    name: mysql-client
#    state: latest
#
#- name: install icinga2-ido-mysql
#  package:
#    name: icinga2-ido-mysql
#    state: latest


- name: restart Icinga2
  service:
    name: icinga2
    state: restarted
